--liquibase formatted sql

--changeset KorolchukVladislav:1
create table sock
(
    id         bigint generated by default as identity primary key,
    color      varchar(255),
    cotton_part integer
);

create table coming
(
    id                  bigint generated by default as identity primary key,
    quantity            integer,
    sock_id             bigint references sock (id)
);

create table сonsumption
(
    id       bigint generated by default as identity primary key,
    quantity integer,
    sock_id  bigint references sock (id)
);
